### ISSUE TITLE
Minimum log size to file

### ISSUE THREAD

**Issue by DominicHJ** [ZhreShold/zupply#18]
Hi, 
Zupply logger is pretty convenient, you can set a max size for log file like the code down below, though I still got  a problem, I found that the log message created by program won't be saved to log file until it reach at least 8Kb size, if the log message is too short (less than 8kb), it won't be update to log file, I am wondering if there is any setting that can make log file being updated immediately, to story every single log message created by program.Thank you!

logger->attach_sink(log::new_rotate_file_sink("rotate.txt", 4*1024*1024, true));
logger->info("When file exceed 4M, the content will be cleared, backups will be renamed");

**Comment by zhreshold** [comment]
Can you give an example code snipet to reproduce the problem? By design every peny of log will be saved if the sink is flushed and closed properly.

**Comment by DominicHJ** [comment]
#include "zupply.hpp"

int main()
{
    auto my_log = zz::log::get_logger("default");
    my_log->attach_sink(zz::log::new_rotate_file_sink("log.txt", 100*1024, true));
    for(int count = 0; count < 10000; count++) {
        my_log->info("This is a log test, running times: ")  << count;
        sleep(1);
    }
    return 0;
}
/***********************************************************************************/
There will be a "log.txt" file being created when this program start,  this log file keeps empty and the size is 0, until "count = 95", then this log file suddenly have all 95 log messages and the size of this file is 12k. As the program keep running, log file remains 12k, when "count = 190", this log file will be update again.

I compiled and run this porgram in OS: Red Hat Enterprise Linux Server rekease 7.2 (Maipo)
with compiled command:  g++ -std=c++11 log_test.cpp zupply.cpp -o test

**Comment by zhreshold** [comment]
#19 should fix the problem. The root cause is that originally when you terminate with CTRL+C for example, the problem will be terminated no matter what, leaving the logger unflushed. I have hooked the abort signal so it will be properly flushed to log.txt

**Comment by DominicHJ** [comment]
Thank you for your prompt reply!
When I run the program above, log file still won’t be updated immediately, for example,when “count =20”, the log file is still empty, but when I terminate the program with CTRL+C,  like you said, log file records all log messages create by program. So I still got the problem: I can’t get the latest log message from “log.txt ” when the program keeps running, unless I terminate the program by myself.
I also found, when the running program suddenly crashed for some reason like “segmentation fault”(cause by memory overflow for example),  latest log won’t be recorded, I am not sure if this abort signal type can be hooked or not .

**Comment by DominicHJ** [comment]
Thank you for your prompt reply! It works for me now.

In addition, according to my test, there are still 2 problems that confuse me
1) When I run the program above, log file still won’t be updated immediately, for example,when “count =20”, the log file is still empty, when “count” reach to 95, log will be saved automatically, but at anytime when I terminate the program with CTRL+C, like you said, log file records all log messages create by program immediately . So the problem is, It seems we can’t get the latest log message from “log.txt ” when the program keeps running, unless the program is terminated.
2) When the running program suddenly crashed in some case like “segmentation fault”(cause by memory overflow for example), latest log won’t be recorded, may be this abort signal type is special and can not be hooked, I don’t really know.

**Comment by zhreshold** [comment]
The reason is that the sinks are asynchronizely get flushed in order to unblock main thread. 
Using sync method for logger is doable, but will significantly slow down the main thread (your program runtime will be limited by disk IO).

I probably can add an flag so it will force flush everytime you write the log, but I wouldn't expect it's a common usecase. 

Still the best way to handle the log IMO is try-catch mechanism, once your program failed for some reason, you are responsible for it and you determine what to do next (flush the logger or quit no matter what) before it crash.

**Comment by zhreshold** [comment]
Or, if you wish to catch as much signals as possible,  not only `SIGINT`, but many others can be hooked as well: https://github.com/zhreshold/zupply/blob/d0dd5fedee252cb51adb4ee86d4abbe6ba2c9ecb/src/zupply.cpp#L13178

**Comment by DominicHJ** [comment]
You are right, using try-catch would be more reasonable. Really appreciate your patience and all your work on this awesome library ( ^ω^ )
